#start and end date
start_date: 2020-11-24
end_date: 2025-12-31


#all tickers path
all_prices:
 - AAPL
 - MSFT
 - NVDA
 - GM
 - F
 - WMT
 - MCD
 - SBUX
 - TSLA
 - GOOGL
 - SPY
 - QQQ
 - VTI
 - VOO
 - ARKK
 - IWM
 - DIA
 - XLF
 - XLK
 - EFA
 - ^GSPC

#stock tickers
stock_tickers:
 - AAPL
 - MSFT
 - NVDA
 - GM
 - F
 - WMT
 - MCD
 - SBUX
 - TSLA
 - GOOGL


#etf tickers
etf_tickers:
- SPY
- QQQ
- VTI
- VOO
- ARKK
- IWM
- DIA
- XLF
- XLK
- EFA




#sp500 ticker
sp500_ticker: ^GSPC


#risk-free rate
risk_free_rate: 0.005



#data paths
all_prices_path: data/raw/all_prices.csv
stock_prices_path: data/raw/stocks.csv
etf_prices_path: data/raw/etfs.csv
sp500_prices_path: data/raw/sp500_prices.csv


#returns
all_returns: data/processed/returns.csv
stock_returns: data/processed/stock_returns.csv
etf_returns: data/processed/etf_returns.csv
sp500_returns: data/processed/sp500_returns.csv
